brainstormforce/all-in-one-schemaorg-rich-snippets

admin/index.php
functions.php
meta-boxes.php
settings.php

Fixed Article schema issue

---

functions.php

Fixing Error: undefined var

---

admin/index.php
index.php
meta-boxes.php
readme.txt

removed commented code as well as solve conflict with woocommerce

Rebuild final

---

admin/index.php
functions.php

issues related to undefined variable fixes in this branch.

Solving issues related to variable

---

admin/index.php
meta-boxes.php
settings.php

Resloved issues related to WooCommerce, Added option in admin panel to enable/disable WooCommerce setting.

Aiosrs fixes2

---

index.php

Use protocol independent urls when enqueing scripts and styles

---

index.php

Add media.js dependencies

---

js/media.js

Checked wp object present page or not.

added condition to check Wp object

---

css/style.css
functions.php

- Fixed design issues
- Rewrite CSS
- Fixed responsive display issue of product
- Fixed display related issues on frontend
- Fixed item review responsive devices issue
- Removed unwanted testing code

Frontend polishing

---

README.md
admin/css/style.css
index.php
package.json
readme.txt

Fix: Frontend Summary box structure validation issue.
Fix: Editor object undefined issue lead js issue in the page.

Frontend fixes

---

functions.php

Added semicolon in  add_ajax_library function

Added semicolon in  add_ajax_library function

---

functions.php
index.php

Updated action and enqueue files function.

Action issue fix

---

functions.php

Fix: Schema box added before the page content in case of Beaver Builder

---

README.md
index.php
readme.txt

* Fix: Collision with Page Builder by SiteOrigin.

updated version number

---

functions.php

updated string to product availability according to google requirement
- in_stock -> InStock
- out_of_stock -> OutOfStock
- instore_only -> InStoreOnly

updated string to product availability according to google requirement

---

README.md
index.php
readme.txt

* Improvement: Updated product availability strings according to the Google requirement.
* Improvement: Added alt tag to the publisher image for SEMrush plugin compatibility.

Version 1.5.6

---

README.md
index.php
readme.txt

* Improvement: Updated plugin name - `All In One Schema Rich Snippets` to `Schema - All In One Schema Rich Snippets`.

updated plugin name

---

README.md
readme.txt

update WordPress compatibility test version

WordPress compatibility

---

.github/workflows/push-to-deploy.yml

Update the Push to Deploy file.

updated the push to deploy file

---

README.md
admin/bsf-analytics/.gitignore
admin/bsf-analytics/Gruntfile.js
admin/bsf-analytics/assets/css/minified/style-rtl.min.css
admin/bsf-analytics/assets/css/minified/style.min.css
admin/bsf-analytics/assets/css/unminified/style-rtl.css
admin/bsf-analytics/assets/css/unminified/style.css
admin/bsf-analytics/bin/block-commits-with-merge-conflict.sh
admin/bsf-analytics/class-bsf-analytics-stats.php
admin/bsf-analytics/class-bsf-analytics.php
admin/bsf-analytics/composer.json
admin/bsf-analytics/composer.lock
admin/bsf-analytics/package-lock.json
admin/bsf-analytics/package.json
admin/bsf-analytics/phpcs.xml.dist
index.php
languages/all-in-one-schemaorg-rich-snippets.pot
lib/notices/class-astra-notices.php
lib/notices/notices.js
phpcs.xml.dist
readme.txt

New: Users can now share non-personal usage data to help us test and develop better products.

Next release

---

admin/index.php
index.php
init.php

- Improvement: Hardened the security of the plugin.
- Fix: Reset functionality is not working in the backend settings.

Security issue

---

README.md
readme.txt

- Updated WordPress compatibility.

Tested compatibility 5.8

---

.gitignore
README.md
admin/index.php
cghooks.lock
readme.txt

- Checked PHPCS changes
- Tested compatibility with the latest WordPress 5.9 version.

updated the tested up to WP version 5.9

---

README.md
admin/index.php
index.php
package.json
readme.txt

- Fixed - Code updated according to a coding standard.

chore: updated the tested up to WP version 6.0

---

.github/workflows/phpcs.yml
README.md
readme.txt

Tested compatibility with the latest WordPress 6.1 version.

chore: updated the tested up to WP version 6.1

---

README.md
admin/index.php
index.php
package.json
readme.txt

- Nonce verification in all the Reset options
- Check ABSPATH in index.php

Few security fixes

---

README.md
readme.txt

Tested compatibility with the latest WordPress 6.2 version.

chore: updated the tested up to WP version 6.2

---

README.md
css/jquery.rating.css
index.php
package-lock.json
package.json
readme.txt

- Updated tested upto tag
- Fixed star rating layout issue caused by recent changes.

WordPress 6.3 compatibility

---

README.md
readme.txt

No issues found
Updated tested upto tag

EPS-471: WordPress 6.5 testing for AIOSRS plugin

---

README.md
readme.txt

No issues found
Updated tested upto tag

WordPress 6.6 testing for AIOSRS plugin

---

README.md
index.php
languages/all-in-one-schemaorg-rich-snippets.pot
package-lock.json
package.json
readme.txt

- Fixed: Resolved the issue for function _load_textdomain_just_in_time was called incorrectly in WP 6.8.

Fixed Load Textdomain issue 
